POST /api/products/1 HTTP/1.1
Host: localhost:8000
Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

Content-Disposition: form-data; name="name"

test2
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"

3
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="sell_price"

5
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="buy_price"

5
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stock"

6
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="user_id"

43
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="visits"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW--
GET localhost:8000/api/products?user_id={{userId}}
